### ISSUE TITLE
tst-raw-sendto

### ISSUE THREAD

**Issue by embbo** [linux-can/can-tests#1]
Hi All,
I am calling "tst-bcm-rx-sendto.c"  from C code, it works fine but it runs in shell program . I have to use "ctr-c" to cancel it. Is there any file, which can call from C programe as intruppt to read can.

**Comment by marckleinebudde** [comment]
Which program do you have to cancel with `ctrl+c`? `tst-raw-sendto` simply sends a CAN frame to an interface and quits, it doesn't block or wait on any `ctrl+c`
I suggest not to call `tst-raw-sendto` from your C program, but better open a socket and send/recevice data to/from it directly.

**Comment by embbo** [comment]
if I call "tst-raw-send "to from my C code it starts but i want to close it automatically after reading from can.

**Comment by marckleinebudde** [comment]
`tst-raw-send` just sends a single CAN frame and then exits, independent if you read a CAN frame or not.

**Comment by marckleinebudde** [comment]
As suggested before, open a `socket()` and use `read()`, `recv` or `recvfrom` to read from it, don't call a compiled C program from your application.
